<br><br>
<img src="./gambar/Logo.png" alt="dcs" height="200" width="200"><br><br>
<b>CP IBanking</b>
<hr class="haer">
<p>&nbsp; Internet Banking Mudah, Aman, dan &nbsp; &emsp; &emsp;  &emsp; &emsp; Terpercaya</p>
<br>
<form name="form1"  method="post">
    <?php echo $err ?>
    <p id="LoginAdmin">&nbsp; Login</p>
    <input type="text" name="nama" id="nama" placeholder="Username"><i style="color:red;" id="nama1"></i>
    <br><br>
    <input type="password" name="passwd" id="password" placeholder="Password"><i style="color:red;" id="password1"></i>
    <br><br>
    <input type="submit" value="Login" name="login" id="submit">
    <input type="reset" value="Reset" name="reset" id="reset">
</form>
