<div class="header">
    <a href="../public/index.php"><img src="../gambar/Logo.png" alt="dcs" width="45" height="48" id="dcs"></a>
    <img src="../gambar/ebanking.png" alt="dcs" width="280" height="50" id="dc">
</div>
<div class="menu">
    <ul>
        <li class="left"><a href="../public/index.php">Beranda</a></li>
        <li class="left"><a href="addCustomer.php">Add</a></li>

        <li class="right"><a class= "active" href="../logout.php">Logout</a></li>
    </ul>
</div>
