<div class="header">
    <a href="Index.php"><img src="../gambar/Logo.png" alt="dcs" width="45" height="48" id="dcs"></a>
    <img src="../gambar/ebanking.png" alt="dcs" width="280" height="50" id="dc">
</div>
<div class="menu">
    <ul>
        <li><a href="../public/index.php">Beranda</a></li>
        <li><a href="daftar_transaksi.php">Daftar Transaksi</a></li>
        <li><a href="transfer.php">Transfer</a></li>
        <li><a href="editPass.php">Edit</a></li>
        <li><a href="../logout.php">Logout</a></li>
    </ul>
</div>
